# Generated by Django 4.0.4 on 2022-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_counter_cunter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cunter',
            new_name='Counter',
        ),
    ]
